# ~/.tmuxinator/base.yml

name: base
root: ~

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

windows:
  - base: clear
